---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - ./cluster.yaml
  - ./secret.sops.yaml
  - ./external-secret.yaml
  - ./scheduledbackup.yaml
  #- ./prometheusrule.yaml
