---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 1password.yaml
  - authentik-charts.yaml
  - bitnami-charts.yaml
  - bjw-s.yaml
  - cloudnative-pg.yaml
  - external-secrets.yaml
  - grafana-charts.yaml
  - hajimari.yaml
  - immich-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - kurereboot-charts.yaml
  - longhorn-charts.yaml
  - metallb-charts.yaml
  - nextcloud-charts.yaml
  - nvidia-charts.yaml
  - nvidia-device-plugin-charts.yaml
  - prometheus-community-charts.yaml
