# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 1password
  - authentik
  - cert-manager
  - cloudnative-pg
  - default
  - external-secrets
  - freshrss
  - home
  - immich
  - ingress
  - kube-system
  - longhorn-system
  - media
  - metallb-system
  - minio
  - mealie
  - monitoring
  - nvidia-device-plugin
  - obsidian-couchdb
  - ollama
  - opencloud
  - paperless
  - photoprism
  - proxmox-csi
  - searxng
  - syncthing
