---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-bulk-metadata-pvc
  namespace: garage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: proxmox-csi-ext4-ssd-zfs
  volumeMode: Filesystem
  volumeName: pvc-cdfe370b-d5d0-488f-976e-9f35f27b81b
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-garage-bulk-pv
  namespace: garage
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nfsvers=4
    - port=2049
  nfs:
    path: /dumpster/backups/garage
    server: "${NFS_SERVER}"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-garage-bulk-pvc
  namespace: garage
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: nfs-garage-bulk-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-bulk-metadata-testonly-pvc
  namespace: garage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: proxmox-csi-ext4-ssd-zfs