---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - ./pvc.yaml
  #- ./cluster.yaml  # TODO: Enable after verifying storage works
  - ./secret.sops.yaml
  - ./external-secret.yaml
  - ./scheduledbackup.yaml
  #- ./prometheusrule.yaml
